In [1]:

import numpy as np
# que operaciones se pueden hacer tanto en un arregloe de numpy como en una lista , dar ejemplos.
lista = [1,2,3,4,5,6,7,8,9]

arreglo= np.array(lista)

print(arreglo)

[1 2 3 4 5 6 7 8 9]


In [2]:
arreglo2=np.array([[1,2,3,4,5,6,7,8,9],[True,False,True,True,False,True,True,False,True],["uno", "dos","tres","uno", "dos","tres","uno", "dos","tres"]])

print(arreglo2)

[['1' '2' '3' '4' '5' '6' '7' '8' '9']
 ['True' 'False' 'True' 'True' 'False' 'True' 'True' 'False' 'True']
 ['uno' 'dos' 'tres' 'uno' 'dos' 'tres' 'uno' 'dos' 'tres']]


In [22]:
#arreglo del cero al 9

arre = np.arange(10)
print(arre)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
ari = np.linspace(0,9,100)

print(ari)

print(len(ari))

In [41]:
op= np.arange(10,101)

div_3=(op%3 ==0)


op[div_3]=-1
print(op)

toto=np.array([1,2,3,4,5,8])

toto.sum()


[ 10  11  -1  13  14  -1  16  17  -1  19  20  -1  22  23  -1  25  26  -1
  28  29  -1  31  32  -1  34  35  -1  37  38  -1  40  41  -1  43  44  -1
  46  47  -1  49  50  -1  52  53  -1  55  56  -1  58  59  -1  61  62  -1
  64  65  -1  67  68  -1  70  71  -1  73  74  -1  76  77  -1  79  80  -1
  82  83  -1  85  86  -1  88  89  -1  91  92  -1  94  95  -1  97  98  -1
 100]


23

In [45]:
nwe = np.full((5,10),0)

nwe

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [49]:
nwe[[1,3],:]=1
nwe[:,[2,7]]=2

print(nwe)

[[0 0 2 0 0 0 0 2 0 0]
 [1 1 2 1 1 1 1 2 1 1]
 [0 0 2 0 0 0 0 2 0 0]
 [1 1 2 1 1 1 1 2 1 1]
 [0 0 2 0 0 0 0 2 0 0]]
